name: "Gradle Wrapper"

on:
  pull_request:
    branches:
      - main

jobs:
  validation:
    name: "Validate"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.example }}
    strategy:
      matrix:
        example: [ android ]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: gradle/wrapper-validation-action@v3